### ISSUE TITLE
【Component】User画面作成 - 4H

### ISSUE THREAD

**Issue by shhymmt** [nino-plus/course-maker#11]
【実装場所】
ShellModule> ShellRouting> UserModule

【機能】
- [ ] 【Service】getUser( )機能実装 - 2H #15
- [ ] 【Service】getCoursesByUid( )機能実装 - 2H #22
- [ ] - [ ] 【Service】updateUser( ), deleteUser( )機能実装 - 2H #16
- アカウントネーム変更
- アバター画像変更
【構成】
UserComponent
ユーザーが作成したコースの表示には、CourseCardComponentを使う
